datasets:
  brain-mri-3d:
    data_type: images
    build_info:
      transform: None
      img_path: /data/changsun/data/MRI/brain/brain_MRI_volume/
      txt_path: /data/changsun/data/MRI/brain/mri_3d_report.csv
