datasets:
  ct-seg:
    data_type: images
    build_info:
      size: None
      transform: None
      img_path: /home/bispl/changsun/data/ct-for-detect-seg/ct.h5 
      txt_path: /home/bispl/changsun/data/ct-for-detect-seg/ct_report.csv
      