datasets:
  rectal-mri-3d:
    data_type: images
    build_info:
      transform: None
      img_path: /scratch/slurm-user3/changsun/data/brain_MRI_volume/
      txt_path: /scratch/slurm-user3/changsun/data/brain_MRI_label/mri_3d_report.csv
