datasets:
  rectal-mri-3d:
    data_type: images
    build_info:
      transform: None
      img_path: /data/changsun/data/MRI/rectal/rectal_MRI_volume/
      txt_path: /data/changsun/data/MRI/rectal/202301_MRI_impression_final.json
