datasets:
  rectal-mri-3d:
    data_type: images
    build_info:
      transform: None
      img_path: /scratch/slurm-user3/changsun/data/rectal_MRI_volume
      txt_path: /scratch/slurm-user3/changsun/data/rectal_MRI_label/formatted_rectal_mri_report.json
